Revert "perf report: Add warning when libunwind not compiled in"
BugLink: https://bugs.launchpad.net/bugs/1858798

This reverts commit 800d3f561659b5436f8c57e7c26dd1f6928b5615 upstream.

This commit introduces a build failure in tools/perf on environments
that don't have libunwind installed.

[...]
builtin-report.c: In function ‘report__setup_sample_type’:
builtin-report.c:289:6: error: ‘dwarf_callchain_users’ undeclared (first
use in this function)
  if (dwarf_callchain_users) {
      ^
[...]

The variable 'dwarf_callchain_users' was introduced by eabad8c6856f
"perf unwind: Do not look just at the global callchain_param.record_mode"
which as of now hasn't been backported to stable linux-4.4.y. So revert
this commit to fix the build failure.

Signed-off-by: Kleber Sacilotto de Souza <kleber.souza@canonical.com>
Acked-by: Stefan Bader <stefan.bader@canonical.com>
Acked-by: Colin Ian King <colin.king@canonical.com>
Signed-off-by: Connor Kuehl <connor.kuehl@canonical.com>